### ISSUE TITLE
Add chapter titles, section/subsection numbering?

### ISSUE THREAD

**Issue by davidlmobley** [kofkeLab/tutorials#3]
@kofke - would you be opposed to me adding chapter titles and section/subsection numbering in the material on here? Thinking of using it in a course which is not identical to yours, it would probably be easiest if I could say, "Read the chapter on ... and focus on sections (number) to (number)..."

**Comment by kofke** [comment]
No objection.  That would be a useful addition, thanks.

**Comment by davidlmobley** [comment]
I'll do that. I'm tempted to also switch to a more polished-looking LaTeX template at the same time. I think it also might be a good idea to indicate authors on a by-chapter basis to allow us to easier bring in additional authors and acknowledge their contributions appropriately without having to keep tons of info on the main page, so maybe I can handle that at the same time.

**Comment by kofke** [comment]
This is all ok with me.  I haven't invested anything in the look-and-feel or organizational elements, so anything that brings your expertise and time to that will surely lead to improvement.

**Comment by davidlmobley** [comment]
Have a quick look at this PDF and see if you like the style; I've basically just pulled the LiveCoMS LaTeX template and made a very minor adjustment or two: https://github.com/MobleyLab/Mol-Sim-Intro/blob/master/HardSphereMD.pdf

**Comment by kofke** [comment]
That’s looks great David.  I’m not sure the content will live up to the quality of the formatting now! (but we can work on that).  It certainly is a lot more inviting with some effort toward presentation.  

I like your judgement and style, so keep it up!

**Comment by davidlmobley** [comment]
Closed via #10
