### ISSUE TITLE
OK with draw.io for figure updates?

### ISSUE THREAD

**Issue by davidlmobley** [kofkeLab/tutorials#6]
Some of the figures will need updating due to resolution issues, etc. Are you OK with using draw.io (free online figure tool, kind of like Google Docs for figures) for these?  It produces HTML graphics which are very portable and can be exported to a wide variety of formats so they should be stable and updatable again in perpetuity, even if draw.io goes away.

If so I could port some of the figures there/make updated versions there.

**Comment by kofke** [comment]
I'd be delighted if you could do this, if you don't mind. Thanks.

**Comment by davidlmobley** [comment]
No problem. Might not be the speediest thing, but I'll do it.
